### PR TITLE
Fix modify on copy is not working

### LINKED ISSUE #11: Does not work
As the title says, it's not working, CTRL+C give X.com link, not VXtwitter links on CTRL+V

### PR DESCRIPTION
**Pull request by takurinton**
close https://github.com/thevenuz/xify/issues/11

The modify on copy functionality was lost because document.location.href was not obtained.
This PR fixes that.

### CODE REVIEW

File: src/copy.js [hunk 1]
```diff
@@ -13,25 +13,33 @@ chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
 const FIX_TARGET = /twitter\.com|x\.com/g
 
 document.addEventListener('copy', e => {
-  target = window.getSelection().toString()
-
-  if (!target) {
-    return;
+  // ctrl+c or cmd+c copy
+  target = document.location.href;
```
Comment (takurinton) [inline src/copy.js]: To avoid complexity, define each behavior separately window.getSelection().toString() and document.location.href

**Comment by thevenuz** [comment]
@takurinton I noticed that when there is text selected and use copy shortcut, link is getting copied instead of the text.

I made a change to first check if there's any selected text, and if there's no selected text, proceed to copying the vx/fxtwitter link. How does this look for you? Do you see any possible scenarios where this might break?

**Comment by thevenuz** [comment]
@takurinton Gonna merge this now. When you're active, let me know if you see any issues.

**Comment by takurinton** [comment]
@thevenuz 
Sorry, I missed your comment.
When I copy the link from the share button, it doesn't seem to work properly.
I knew that this pull request was incomplete, but I left it as it was because I wanted to confirm the issue with the issue creator first. Sorry.
You might want to consider reverting it and seeing how it goes!

**Comment by thevenuz** [comment]
@takurinton Hmm, weird that it works for me. Are you using the share button from the home page? or the share button after opening the post?

**Comment by takurinton** [comment]
@thevenuz 

I wrote about my current situation.

- when to use the share button
  - vxtwitter.com will be substituted, but the url will be the current url
    - i.e.) if you use the share button on x.com/home(home page), it will become vxtwiiter.com/home
    - i.e.) copying x.com/status/xxx will result(after opening the post) in vxtwitter.com/status/xxx
    - the latter may seem like a good idea at first glance, but this is not the intended behavior
- copy the URL directly from the address bar
  - in this case the url is not replaced

**Comment by dwahgon** [comment]
i had accidentally made a duplicate issue #13 , but this issue is still very much present in the current version

**Comment by takurinton** [comment]
@thevenuz FYI @dwahgon 
I think simply reverting this will solve the problem, right?

**Comment by takurinton** [comment]
I tried creating https://github.com/thevenuz/xify/pull/14 👀
