### PR TITLE
Fix replace x.com with vxtwitter.com

### LINKED ISSUE #5: x.com not converted to vxtwitter.com
Hello!
Thank you for the wonderful extension! I use this plugin every day!!:)

Not so long ago, twitter used to redirect from x.com to twitter.com, but this is no longer the case.
This extension currently does not support replacing x.com with vxtwitter.com.

I would like to implement an implementation that solves this.

### PR DESCRIPTION
**Pull request by takurinton**
close https://github.com/thevenuz/xify/issues/5

### CODE REVIEW

File: src/copy.js [hunk 1]
```diff
@@ -22,15 +22,15 @@ document.addEventListener('copy', e => {
 });
 
 const updateLink = clipboardData => {
-  var modifiedLink = clipboardData.replace('twitter', 'vxtwitter');
+  var modifiedLink = clipboardData.replace(/twitter\.com|x\.com/g, 'vxtwitter.com');
```
Comment (takurinton) [inline src/copy.js:25]: If you replace x with vxtwitter, it may unintentionally hit characters in usernames, etc., so we include .com as well.

**Comment by thevenuz** [comment]
@takurinton Thanks for the contribution! Reviewed the changes and they look good. Merging this.

**Review by thevenuz — APPROVED** [review]

**Comment by takurinton** [comment]
@thevenuz 
Hello.
Thank you for merging this pull request.
It looks like this hasn't been released yet, but when is it expected to be released?

**Comment by thevenuz** [comment]
@takurinton  Hello. Published to the chrome store, so the changes should be reflected soon.
Thanks!
